In [5]:
import anndata as ad
import numpy as np
import matplotlib.pyplot as plt
import h5py
import pandas as pd
import os
import scanpy as sc

In [6]:
import os
print(os.getcwd())

/home/azweig/projects/finfm/benchmark/flow_matching_minimal

In [7]:
df_train = pd.read_hdf("data/train_cite_inputs.h5")
df_train

gene_id,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
cell_id,,,,,,,,,,,,,,,,,,,,,
45006fe3e4c8,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,4.090185,0.000000
d02759a80ba2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.039545,0.0,0.0,0.000000,0.000000,0.000000,0.000000
c016c6b0efa5,0.0,0.0,0.0,0.0,0.0,3.847321,0.000000,3.847321,3.847321,0.000000,...,0.000000,0.000000,3.847321,4.529743,0.0,0.0,0.000000,3.847321,3.847321,0.000000
ba7f733a4f75,0.0,0.0,0.0,0.0,0.0,0.000000,3.436846,3.436846,0.000000,0.000000,...,3.436846,0.000000,4.113780,5.020215,0.0,0.0,0.000000,3.436846,4.113780,0.000000
fbcf2443ffb2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.196826,0.000000,0.000000,...,0.000000,4.196826,4.196826,4.196826,0.0,0.0,3.518610,4.196826,3.518610,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650ee456f0f3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,4.397535,4.397535,5.084510,0.0,0.0,0.000000,0.000000,4.397535,4.397535
cc506e7707f5,0.0,0.0,0.0,0.0,0.0,0.000000,3.981467,4.665241,0.000000,0.000000,...,3.981467,0.000000,4.665241,3.981467,0.0,0.0,0.000000,0.000000,3.981467,0.000000
a91f1b55a520,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.497696,0.000000,4.497696,...,0.000000,0.000000,0.000000,4.497696,0.0,0.0,3.815622,4.497696,0.000000,0.000000
3a9882c98205,0.0,0.0,0.0,0.0,0.0,0.000000,3.900907,0.000000,0.000000,4.583891,...,0.000000,0.000000,4.583891,4.985945,0.0,0.0,0.000000,0.000000,0.000000,3.900907
c91b6b2ccd3d,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.189502,0.000000,0.000000,4.189502,0.0,0.0,0.000000,0.000000,4.189502,4.189502

In [8]:
df_test = pd.read_hdf("data/test_cite_inputs.h5")
df_test

gene_id,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
cell_id,,,,,,,,,,,,,,,,,,,,,
c2150f55becb,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,4.090185,0.000000
65b7edf8a4da,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.039545,0.000000,0.0,0.00000,0.000000,0.000000,0.000000
c1b26cb1057b,0.0,0.0,0.0,0.0,0.0,3.847321,0.000000,3.847321,3.847321,0.000000,...,0.000000,0.000000,3.847321,4.529743,0.000000,0.0,0.00000,3.847321,3.847321,0.000000
917168fa6f83,0.0,0.0,0.0,0.0,0.0,0.000000,3.436846,3.436846,0.000000,0.000000,...,3.436846,0.000000,4.113780,5.020215,0.000000,0.0,0.00000,3.436846,4.113780,0.000000
2b29feeca86d,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.196826,0.000000,0.000000,...,0.000000,4.196826,4.196826,4.196826,0.000000,0.0,3.51861,4.196826,3.518610,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a9b4d99f1f50,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,3.719836,...,0.000000,0.000000,0.000000,3.719836,0.000000,0.0,0.00000,0.000000,3.719836,0.000000
0e2c1d0782af,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,4.026206,0.000000,...,4.026206,0.000000,0.000000,4.026206,0.000000,0.0,0.00000,0.000000,4.710393,0.000000
a3cbc5aa0ec3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.306634,0.000000,0.000000,0.0,0.00000,4.306634,6.933096,4.993019
75b350243add,0.0,0.0,0.0,0.0,0.0,0.000000,3.624848,3.624848,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.624848,3.624848,0.0,0.00000,3.624848,0.000000,0.000000
ad5a949989b2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,4.452700,0.000000,3.377115,...,3.377115,3.377115,0.000000,4.737466,0.000000,0.0,0.00000,0.000000,0.000000,0.000000

In [9]:
import phate

In [10]:
df_meta = pd.read_csv("data/metadata.csv")
df_meta

             cell_id  day  donor cell_type technology
0       c2150f55becb    2  27678       HSC    citeseq
1       65b7edf8a4da    2  27678       HSC    citeseq
2       c1b26cb1057b    2  27678      EryP    citeseq
3       917168fa6f83    2  27678      NeuP    citeseq
4       2b29feeca86d    2  27678      EryP    citeseq
...              ...  ...    ...       ...        ...
281523  96a60b026659   10  31800    hidden   multiome
281524  d493e546991e   10  31800    hidden   multiome
281525  05666c99aa48   10  31800    hidden   multiome
281526  121f946642b5   10  31800    hidden   multiome
281527  b847ba21f59f   10  31800    hidden   multiome

[281528 rows x 5 columns]

In [11]:
donor = 13176
days_to_keep = [2,3,4,7]
df_donor_meta = df_meta[(df_meta['donor']==donor) & (df_meta['technology']=="citeseq") & (df_meta['cell_type']!="unknown") & df_meta['day'].isin(days_to_keep)]
print(df_donor_meta.shape)

(29394, 5)

In [12]:
donor_cell_ids = df_donor_meta['cell_id'].unique().tolist()
print(len(donor_cell_ids))

unique_days = df_donor_meta['day'].unique().tolist()
print(unique_days)

unique_cell_types = df_donor_meta['cell_type'].unique().tolist()
print(unique_cell_types)

29394
[2, 3, 4, 7]
['NeuP', 'EryP', 'HSC', 'MasP', 'MkP', 'MoP', 'BP']

In [13]:
# Filter df_train, df_test on donor_cell_ids
df_train_donor = df_train[df_train.index.isin(donor_cell_ids)]
df_test_donor = df_test[df_test.index.isin(donor_cell_ids)]

print(df_train_donor.shape)
print(df_test_donor.shape)

(22199, 22050)
(7195, 22050)

In [14]:

df_all = pd.concat([df_train_donor, df_test_donor])

In [15]:
df_all

gene_id,ENSG00000121410_A1BG,ENSG00000268895_A1BG-AS1,ENSG00000175899_A2M,ENSG00000245105_A2M-AS1,ENSG00000166535_A2ML1,ENSG00000128274_A4GALT,ENSG00000094914_AAAS,ENSG00000081760_AACS,ENSG00000109576_AADAT,ENSG00000103591_AAGAB,...,ENSG00000153975_ZUP1,ENSG00000086827_ZW10,ENSG00000174442_ZWILCH,ENSG00000122952_ZWINT,ENSG00000198205_ZXDA,ENSG00000198455_ZXDB,ENSG00000070476_ZXDC,ENSG00000162378_ZYG11B,ENSG00000159840_ZYX,ENSG00000074755_ZZEF1
cell_id,,,,,,,,,,,,,,,,,,,,,
08a6f9047e1f,0.0,0.0,0.0,0.0,0.0,0.0,3.451580,0.000000,0.000000,0.000000,...,0.000000,4.528836,3.451580,5.035335,0.000000,0.000000,4.128753,0.000000,4.128753,3.451580
dc33db8b968f,0.0,0.0,0.0,0.0,0.0,0.0,4.264111,0.000000,0.000000,0.000000,...,0.000000,3.584930,4.264111,3.584930,0.000000,0.000000,0.000000,3.584930,0.000000,3.584930
bb17cbbb7869,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,3.884389,0.000000,...,3.884389,0.000000,0.000000,4.567203,0.000000,0.000000,3.884389,0.000000,0.000000,0.000000
608afab25c95,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,4.199862,0.000000,0.000000,...,0.000000,0.000000,0.000000,5.288425,0.000000,0.000000,0.000000,0.000000,4.199862,0.000000
f0a5edc0a949,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.234367,0.000000,0.000000,0.000000,3.555605,5.476727,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
df9aa1771f5e,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.566002,4.930867,0.000000,3.566002,0.000000,0.000000,3.566002,3.566002
2de915de2730,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.796664
71c79a403e17,0.0,0.0,0.0,0.0,0.0,0.0,4.267572,0.000000,0.000000,4.267572,...,0.000000,4.267572,4.267572,4.953687,0.000000,0.000000,0.000000,4.267572,4.267572,0.000000
7e0a56ea890d,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,3.630016,0.000000,0.000000,3.630016,3.630016,0.000000,3.630016,4.309816,4.996223,0.000000
e7f7a547d511,0.0,0.0,0.0,0.0,0.0,0.0,4.120462,0.000000,0.000000,3.443422,...,3.443422,4.120462,4.120462,5.716825,0.000000,0.000000,4.120462,0.000000,4.520500,0.000000

In [17]:
adata = sc.AnnData(df_all)
adata.var_names = df_all.columns
adata.obs_names = df_all.index
adata.obs['donor'] = donor
adata.obs['technology'] = 'citeseq'
adata.obs['cell_id'] = df_all.index
# adata.var['feature_name'] = df_all.columns
adata

AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id'

In [18]:
# pair day with cell id
cellid2day = {cell_id: day for cell_id, day in zip(df_donor_meta['cell_id'], df_donor_meta['day'])}
adata.obs['day'] = [cellid2day[cell_id] for cell_id in adata.obs['cell_id']]

print(adata)

AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id', 'day'

In [19]:
# pair cell_type with cell id
cellid2celltype = {cell_id: cell_type for cell_id, cell_type in zip(df_donor_meta['cell_id'], df_donor_meta['cell_type'])}
adata.obs['cell_type'] = [cellid2celltype[cell_id] for cell_id in adata.obs['cell_id']]

print(adata)

AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id', 'day', 'cell_type'

In [20]:
day_class = np.unique(adata.obs['day'].tolist())
print(day_class)

day2class = {day: i for i, day in enumerate(day_class)}
adata.obs['day_class'] = [day2class[day] for day in adata.obs['day']]
print(adata)

[2 3 4 7]
AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id', 'day', 'cell_type', 'day_class'

In [21]:
adata.obs['day_class'].unique()

array([0, 1, 2, 3])

In [22]:
sc.pp.highly_variable_genes(adata, n_top_genes=1000)
adata

AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id', 'day', 'cell_type', 'day_class'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg'

In [23]:
adata.X[:,adata.var['highly_variable']].shape

(29394, 1000)

In [24]:
sc.tl.pca(adata, n_comps=100)
adata

AnnData object with n_obs × n_vars = 29394 × 22050
    obs: 'donor', 'technology', 'cell_id', 'day', 'cell_type', 'day_class'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'

In [25]:
from scipy.spatial.distance import pdist, squareform
from scipy import sparse as sp

def convert_data(X, colors, seed=42, test_size=0.1, knn=5, t='auto', n_components=3):
    # if X is sparse, convert to dense
    if sp.issparse(X):
        X = X.toarray()
        
    phate_op = phate.PHATE(random_state=seed, t=t, n_components=n_components, knn=knn)
    phate_data = phate_op.fit_transform(X)
    
    print("Computing distances...")

    dists = squareform(pdist(phate_op.diff_potential))

    return dict(
        data=X,
        colors=colors,
        dist=dists,
        phate=phate_data
    )

data = convert_data(adata.obsm['X_pca'][:,:100], np.array(adata.obs['day_class'].tolist()))
# data = convert_data(adata.X[:,adata.var['highly_variable']], np.array(adata.obs['day_class'].tolist()))

Calculating PHATE...
  Running PHATE on 29394 observations and 100 variables.
  Calculating graph and diffusion operator...
    Calculating KNN search...
    Calculated KNN search in 42.90 seconds.
    Calculating affinities...
    Calculated affinities in 11.72 seconds.
  Calculated graph and diffusion operator in 54.65 seconds.
  Calculating landmark operator...
    Calculating SVD...
    Calculated SVD in 1.84 seconds.
    Calculating KMeans...
    Calculated KMeans in 1.24 seconds.
  Calculated landmark operator in 3.59 seconds.
  Calculating optimal t...
    Automatically selected t = 16
  Calculated optimal t in 0.53 seconds.
  Calculating diffusion potential...
  Calculated diffusion potential in 0.12 seconds.
  Calculating metric MDS...

/home/azweig/miniconda3/envs/dmae/lib/python3.11/site-packages/sklearn/manifold/_mds.py:299: FutureWarning: The default value of `normalized_stress` will change to `'auto'` in version 1.4. To suppress this warning, manually set the value of `normalized_stress`.
  warnings.warn(

  Calculated metric MDS in 7.42 seconds.
Calculated PHATE in 66.31 seconds.
Computing distances...

In [26]:
print(data['data'].shape)
print(data['colors'].shape)
print(data['dist'].shape)
print(data['phate'].shape)

(29394, 100)
(29394,)
(29394, 29394)
(29394, 3)

In [27]:
np.savez("data/cite_all_D-100_d-3_pca.npz", data=data['data'], colors=data['colors'], dist=data['dist'], phate=data['phate'])

In [ ]:
#TODO: we need to save the whole adata object preprocessed